# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: Apache-2.0
"""``migrations.lock.json`` is derived, never authored — tier 0, no cluster.

MR-6 lock 1. The manifest is generated by walking the tree and resolving every file
against ``migrations.allocation.toml``. What has to be true, and what these cases assert:

* it is a **projection**, so hand-editing it is detected rather than tolerated;
* every disagreement is reported, not just the first, because a manifest 156 files behind
  otherwise costs 156 regenerate-and-rerun cycles to learn one thing;
* it is **byte-stable** across regenerations on any platform, or ``--check`` fails on CI
  for a file nobody edited;
* and the *committed* manifest is current, which is the only assertion that makes the
  other three worth anything.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from trappoint_migrate.errors import UsageError
from trappoint_migrate.lockfile import (
    build_lock,
    counsel_gated_files,
    lock_path_for,
    render_lock,
    verify_lock,
    write_lock,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
MAINLINE_TREE = REPO_ROOT / "verticals" / "mainline" / "db" / "migrations"

ALLOCATION = """\
[[band]]
first = "0001"
last = "0009z"
owner = "kernel/example"
mode = "rendered"
contents = "the rendered band"

[[band]]
first = "0010"
last = "9999z"
owner = "vertical/example"
mode = "authored"
contents = "the authored band"
"""

RENDERED = """\
-- SPDX-License-Identifier: Apache-2.0
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: the schema exists before anything it contains.
--
-- @rendered-by  trappoint render
-- @template     packages/trappoint-sql/templates/0001_schemas.sql.j2
--
CREATE SCHEMA mainline;
"""

AUTHORED = """\
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI17
-- I: I13
-- COUNSEL-GATED: yes (G0) · DEFAULT: conservative · ADR: docs/adr/0001-g0-counsel.md
-- RATIONALE: the disposition family's shape depends on a legal answer.
--
CREATE TABLE mainline.disposition (id UUID PRIMARY KEY);
"""


@pytest.fixture
def tree(tmp_path: Path) -> Path:
    """A two-file migration tree with its allocation beside it, as MR-5/MR-6 require."""
    root = tmp_path / "db" / "migrations"
    root.mkdir(parents=True)
    (tmp_path / "db" / "migrations.allocation.toml").write_text(ALLOCATION, encoding="utf-8")
    (root / "0001_schema_mainline.sql").write_text(RENDERED, encoding="utf-8")
    (root / "0066_disposition.sql").write_text(AUTHORED, encoding="utf-8")
    return root


def test_the_manifest_records_what_the_tree_says(tree: Path) -> None:
    document = build_lock(tree)
    by_file = {entry["file"]: entry for entry in document["migrations"]}

    rendered = by_file["0001_schema_mainline.sql"]
    assert rendered["mode"] == "rendered"
    assert rendered["band"] == "0001-0009z"
    assert rendered["owner"] == "kernel/example"
    assert rendered["template"] == "packages/trappoint-sql/templates/0001_schemas.sql.j2"
    assert rendered["invariants"] == ["MI01", "I01"]
    assert rendered["counsel_gated"] is False

    authored = by_file["0066_disposition.sql"]
    assert authored["mode"] == "authored"
    assert authored["owner"] == "vertical/example"
    assert authored["template"] is None
    assert authored["counsel_gated"] is True

    assert document["counts"] == {
        "files": 2,
        "rendered": 1,
        "authored": 1,
        "counsel_gated": 1,
        "counsel_gated_undeclared": 0,
        "bands_occupied": 2,
    }


def test_the_counsel_gated_set_is_queryable(tree: Path) -> None:
    assert counsel_gated_files(build_lock(tree)) == ["0066_disposition.sql"]


def test_a_header_that_does_not_answer_counsel_records_null_not_no(tree: Path) -> None:
    """Silence is not 'no'. A manifest that defaulted it would manufacture a claim."""
    (tree / "0067_quiet.sql").write_text(
        AUTHORED.replace(
            "-- COUNSEL-GATED: yes (G0) · DEFAULT: conservative · "
            "ADR: docs/adr/0001-g0-counsel.md\n",
            "",
        ),
        encoding="utf-8",
    )
    document = build_lock(tree)
    entry = next(e for e in document["migrations"] if e["file"] == "0067_quiet.sql")
    assert entry["counsel_gated"] is None
    assert document["counsel_gated_undeclared"] == ["0067_quiet.sql"]


def test_the_render_is_byte_stable_across_two_builds(tree: Path) -> None:
    assert render_lock(build_lock(tree)) == render_lock(build_lock(tree))


def test_write_then_verify_is_clean(tree: Path) -> None:
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    assert verify_lock(path, tree) == []


def test_the_written_file_uses_lf_endings_on_every_platform(tree: Path) -> None:
    """A CRLF manifest makes `--check` red on a Linux runner for a file nobody edited."""
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    assert b"\r\n" not in path.read_bytes()


def test_a_new_file_on_disk_is_reported_as_stale(tree: Path) -> None:
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    (tree / "0070_carried_disposition.sql").write_text(AUTHORED, encoding="utf-8")
    findings = verify_lock(path, tree)
    assert any("0070_carried_disposition.sql is on disk" in f for f in findings)
    assert any("lock --write" in f for f in findings)


def test_a_deleted_file_is_reported_separately_from_a_new_one(tree: Path) -> None:
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    (tree / "0066_disposition.sql").unlink()
    findings = verify_lock(path, tree)
    assert any("in the manifest but not on disk" in f for f in findings)


def test_a_hand_edited_field_is_caught(tree: Path) -> None:
    """The manifest is a projection. Editing it is detected, which is what makes it one."""
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    document = json.loads(path.read_text(encoding="utf-8"))
    document["migrations"][1]["counsel_gated"] = False
    document["migrations"][0]["sha256"] = "0" * 64
    path.write_text(json.dumps(document, indent=1) + "\n", encoding="utf-8")

    findings = verify_lock(path, tree)
    assert any("counsel_gated" in f for f in findings)
    assert any("sha256" in f for f in findings)


def test_every_disagreement_is_reported_not_only_the_first(tree: Path) -> None:
    path = lock_path_for(tree)
    write_lock(path, build_lock(tree))
    for number in ("0071", "0072", "0073"):
        (tree / f"{number}_extra.sql").write_text(AUTHORED, encoding="utf-8")
    findings = verify_lock(path, tree)
    assert sum(1 for f in findings if "is on disk but absent" in f) == 3


def test_an_absent_manifest_is_a_finding_and_not_a_crash(tree: Path) -> None:
    findings = verify_lock(lock_path_for(tree), tree)
    assert len(findings) == 1
    assert "does not exist" in findings[0]


def test_an_empty_tree_refuses_rather_than_writing_an_empty_manifest(tmp_path: Path) -> None:
    """An empty lock and a lock of an empty tree are the same bytes; one is a typo."""
    empty = tmp_path / "db" / "migrations"
    empty.mkdir(parents=True)
    with pytest.raises(UsageError, match="holds no migration files"):
        build_lock(empty)


def test_the_lock_sits_beside_the_tree_never_inside_it(tree: Path) -> None:
    """A `.json` in the apply path is one glob away from being read as a migration."""
    path = lock_path_for(tree)
    assert path.name == "migrations.lock.json"
    assert path.parent == tree.parent


# ── The repository itself ─────────────────────────────────────────────────────────────


@pytest.mark.skipif(not MAINLINE_TREE.is_dir(), reason="the MAINLINE migration tree is absent")
def test_the_committed_manifest_is_current() -> None:
    findings = verify_lock(lock_path_for(MAINLINE_TREE), MAINLINE_TREE, repo_root=REPO_ROOT)
    assert findings == [], "run `trappoint migrate lock --write`"


@pytest.mark.skipif(not MAINLINE_TREE.is_dir(), reason="the MAINLINE migration tree is absent")
def test_no_committed_migration_falls_outside_the_allocation() -> None:
    """MR-6: every number has an owner or it has no file. `0200+` is refused outright."""
    document = build_lock(MAINLINE_TREE, repo_root=REPO_ROOT)
    unowned = [e["file"] for e in document["migrations"] if e["band"] is None]
    assert unowned == []
    terminal = [e["file"] for e in document["migrations"] if e["owner"] == "UNALLOCATED"]
    assert terminal == [], "0200 and above is unallocated; no file may use it"
