-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: CockroachDB has no column-level privileges, so privilege separation is by schema, database or cluster and nothing else (ARCHITECTURE §4); the schema boundary is therefore the first of the three append-only layers, not an organisational convenience.
--
-- migration:  0002_schema_mainline
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §4 (schema zones) · §5.0
-- requires:   0001 mainline_owner
-- sqlstate:   —
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- THE BUSINESS RECORD. Discoverable by design; this is the defence exhibit. Commit DAG, clauses,
-- events, blame, permit, change_request, the gate, the custody ledger, identity, governance.
--
-- `AUTHORIZATION mainline_owner` is the ownership transfer that the lead's map put in 0007, moved
-- to the moment of creation (see 0001 for why). Ownership matters here for one specific reason:
-- an owner is exempt from RLS unless the table also carries `FORCE ROW LEVEL SECURITY`, and it is
-- the owner who can `DROP TRIGGER`. Making the owner a NOLOGIN role that nobody is a member of
-- means the DDL authority for this schema is held by an identity with no credential — DDL is done
-- by an admin provisioning identity that is separately audited, or by `mainline_migrator` under
-- the CREATE privilege GRANTS.yaml gives it, never by an application role.

CREATE SCHEMA mainline AUTHORIZATION mainline_owner;
