-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: The Managed-MCP auditor identity must be reachable by exactly one surface whose every object is shaped to the connector's hard limits, and a schema that contains only views is the only structure that makes "the auditor has no table" checkable in one query.
--
-- migration:  0004_schema_mainline_audit
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §4 (schema zones) · §17 (the Managed-MCP audit surface) · §11.2
-- requires:   0001 mainline_owner
-- sqlstate:   —
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- VIEWS ONLY. Every object in this schema is shaped to ≤ 25 rows and ≤ 10 KiB, because those are
-- the Managed MCP server's response limits and an auditor surface that gets truncated at the
-- transport is an auditor surface that lies by omission. The views are dm-views-rls's band
-- (0200-0279); this file creates only the zone, so that the GRANT naming it in GRANTS.yaml has
-- something to name from migration 0004 onward rather than failing on a fresh cluster.
--
-- `mainline_auditor` holds SELECT on `mainline_audit.v_*` AND NOTHING ELSE, plus INSERT on the
-- single table `mainline_meas.external_attestation`. The probe in test_mi_foundation.py asserts
-- the negative half of that sentence, table by table, because a grant matrix is a claim and a
-- 42501 is evidence.

CREATE SCHEMA mainline_audit AUTHORIZATION mainline_owner;
