-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: Per-named-person distributions must exist somewhere the scored person can reach them (SEC-3 condition 4) and nowhere a machine identity can, and "never an MCP account" is only auditable if the boundary is a named object rather than a convention.
--
-- migration:  0005_schema_mainline_qa
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §4 (schema zones, S14) · §11.2 · §11.5 (the Attribution Rule)
-- requires:   0001 mainline_owner
-- sqlstate:   —
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- VIEWS ONLY, AND NEVER AN MCP ACCOUNT, EVER (S14).
--
-- This is the zone the Attribution Rule creates. SEC-3 permits a derived characterisation of a
-- named human only if the scored person can obtain their own score and its derivation; that is
-- what `mainline_qa.v_my_record` is for, RLS-scoped to CURRENT_USER. It also permits distributions
-- without names, which is why `signer_sub` is a span attribute and never a metric label — a
-- dimension we cannot aggregate on is a dimension we cannot accidentally publish.
--
-- Two roles ever reach this schema: `quality_assurance` and `subject_access`. `mainline_auditor`
-- — the Managed-MCP identity — must not, and test_mi_foundation.py asserts 42501 on it. Every
-- SELECT here writes a ledger entry (`entry_kind='profile_read'`): observing the observer, so that
-- if the profile is produced in discovery it arrives with a signed record of who looked and why.

CREATE SCHEMA mainline_qa AUTHORIZATION mainline_owner;
