-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MAINLINE · 0006c_role_gate.sql
-- CREATE ROLE agent_gate — the gate slot
--
-- MI: MI02
-- I: I02
-- COUNSEL-GATED: no
-- RATIONALE: the kernel's own identity: the only role that materialises an obligation, and
--            the only writer of the subject state machine. IF NOT EXISTS because a role is
--            cluster state, not schema state: a restore does not carry it, two verticals on
--            one cluster legitimately share the agent roles, and re-asserting one must
--            never be an error.
--
-- @rendered-by  trappoint render
-- @template     packages/trappoint-sql/templates/0006_roles.sql.j2
-- @binding      verticals/mainline/vertical.toml
-- DO NOT EDIT. `trappoint render --check` is a zero-diff assertion in CI, so a
-- hand edit here is a red build, not a silent divergence.
--
-- Slot         gate
-- Name         agent_gate   (overridable in [roles] of the binding)

CREATE ROLE IF NOT EXISTS agent_gate;
