-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: Append-only is enforced by three independent layers in the order grants, triggers, RLS; the first layer's base case is that no privilege reaches a MAINLINE zone except by being named in GRANTS.yaml, and `public` is a role every principal holds implicitly.
--
-- migration:  0007_revoke_public_on_mainline_schemas
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §11.2 · §18 (0006-0009) · docs/leads/datamodel.md DM-7
-- requires:   0002-0006 the five schemas
-- sqlstate:   —
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- HONESTY ABOUT WHAT THIS FILE DOES.
--   A schema created by `CREATE SCHEMA` in CockroachDB does not grant anything to `public` by
--   default — unlike the database's built-in `public` schema, which 0008 handles. So on a clean
--   v26.2 this statement revokes a privilege set that is already empty and changes nothing.
--   It ships anyway, for two reasons that are not decoration:
--     1. It is the explicit, dated, blame-carrying statement of the default-deny posture. A
--        reviewer asking "who can touch schema mainline" gets a file, not an absence.
--     2. It is not conditional on the default. A cluster restored from elsewhere, a database
--        created by a tool that pre-grants, or a future release that changes the default all
--        leave this file correct. Relying on a default nobody wrote down is how a zone quietly
--        opens.
--   `REVOKE` on privileges that were never granted is not an error, so the statement is safe on
--   every path.
--
-- The five schemas are revoked in ONE statement because `schema_name_list` in CockroachDB's REVOKE
-- grammar is a comma-separated list. That keeps one-DDL-statement-per-file intact without five
-- near-identical files.

REVOKE ALL ON SCHEMA mainline, mainline_meas, mainline_audit, mainline_qa, mainline_ops FROM public;
