-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: Role membership and object privileges are cluster state that a RESTORE into a new cluster does not carry, so they must be re-asserted and drift-checked on every environment rather than applied once and assumed; this file is the marker that says so at the exact point in the sequence where a reader looks for the GRANT statements and does not find them.
--
-- migration:  0009_grants_are_not_migrations
-- band:       0001-0023 · dm-foundation
-- statements: 1 (a no-op SELECT; this file deliberately creates nothing)
-- source:     docs/leads/datamodel.md DM-7 · ARCHITECTURE.md §11.2 · §18 (0006-0009)
-- requires:   0007, 0008 — the deny posture this marker explains
-- sqlstate:   —
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- WHERE THE GRANTS WENT — read this before looking for them.
--
--   ARCHITECTURE §18 reserves 0006-0009 for "CREATE ROLE + GRANT". DM-7 splits that: only the four
--   statements that are genuinely schema stayed in the migration set —
--
--     0001  CREATE ROLE mainline_owner (NOLOGIN, unassumable)
--     0002-0006  CREATE SCHEMA … AUTHORIZATION mainline_owner   (the ownership transfer)
--     0007  REVOKE ALL ON the five zones FROM public
--     0008  REVOKE CREATE ON SCHEMA public FROM public
--
--   — and everything else became a declarative matrix at verticals/mainline/db/GRANTS.yaml,
--   re-asserted idempotently by `trappoint-migrate grants apply`.
--
--   Three reasons, in descending order of how much they cost to learn the hard way:
--
--   1. A RESTORE into a fresh cluster does not carry role membership or grants. A grant applied
--      once, in migration 0006, is a grant that exists in dev and does not exist in the cluster
--      the restore drill produces — and the drill is a K6 deliverable. Cluster state must be
--      re-asserted, and a forward-only migration is by construction the wrong instrument for
--      something that must be re-asserted.
--   2. Drift is the actual risk. A grant added by hand at 2 a.m. during an incident is invisible
--      to a migration set and visible to a declarative matrix that CI diffs.
--   3. The real control was never the DDL that granted. It is the privilege probe that asserts
--      42501 for every (role, object) pair the matrix does NOT name —
--      tests/integration/schema/test_mi_foundation.py::test_privilege_probe_refuses_ungranted_writes.
--      A GRANT statement is a claim about intent; a 42501 is evidence about behaviour.
--
--   Consequence, accepted openly (datamodel.md DR-8): a freshly migrated cluster is UNUSABLE by
--   the application roles until `grants apply` has run. `trappoint-migrate apply` therefore does
--   not report success unless the matrix was asserted in the same invocation.
--
-- The body below is a no-op SELECT. It creates nothing, and it is here so that the file — and
-- therefore this explanation — carries a version number, a sha256 in migrations.lock.json, and a
-- line in the schema attestation, exactly like every other decision in the band.

SELECT 'roles and grants are cluster state, not migrations — see verticals/mainline/db/GRANTS.yaml (DM-7)' AS grants_are_not_migrations;
