-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI10
-- I: I03
-- COUNSEL-GATED: no
-- RATIONALE: The permit and the change_request are one state machine (S16), and an illegal transition must be a 23503 against `subject_transition` rather than an `if` statement in a service someone can delete, which requires both subjects to be typed by the same closed alphabet.
--
-- migration:  0011_type_subject_state
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §5.0 (verbatim) · §5.5
-- requires:   0002 CREATE SCHEMA mainline
-- sqlstate:   22P02 on an unknown label; 23503 via mainline.subject_transition (0017)
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- DO NOT ADD A STATE. Seven labels, and each one is read by at least one CHECK or FK in a later
-- band. An eighth state is not an additive change: it is a state for which no row exists in
-- `subject_transition`, so every transition into or out of it is refused — which is safe — but it
-- is also a state the merge gate's CHECK has never been shown to refuse, which is not. Adding one
-- is a schema amendment with its own MI entry and its own red test, never a convenience.
--
--   draft                the subject exists; nothing has been recalled against it
--   checks_materialised  recall ran; obligations, if any, are rows
--   dispositioned        every open obligation carries a signed disposition
--   merged               the transition completed. THE EPOCH IS PINNED HERE (I03)
--   suspended            merged, then stopped; still merged for the purposes of history
--   closed               terminal
--   abandoned            terminal, from draft only. Never reachable from merged.
--
-- `merged` is the state the whole product exists to make expensive. Everything before it is
-- ordinary workflow; the transition into it is the one the database refuses.

CREATE TYPE mainline.subject_state AS ENUM
  ('draft', 'checks_materialised', 'dispositioned', 'merged', 'suspended', 'closed', 'abandoned');
