-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI11
-- I: I10
-- COUNSEL-GATED: no
-- RATIONALE: The set of ways a human may clear a precursor is the legal surface of the product, so it is a closed type composite-FK'd to `clearance_legal`; that is what makes "no disposition constructor dismisses a control written by a fatality" a 23503 rather than a policy.
--
-- migration:  0012_type_disposition_kind
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §5.0 (verbatim) · §11.5 (vocabulary hygiene)
-- requires:   0002 CREATE SCHEMA mainline
-- sqlstate:   22P02 on an unknown label; 23503 via mainline.clearance_legal (0018)
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- `mechanism_absent`, NEVER `not_applicable`. This is a vocabulary rule with a legal reason and a
-- CI grep behind it (§11.7). "Not applicable" is a dismissal, and dismissal is disregard, and
-- disregard is the element the offence provisions turn on. "The mechanism is absent" is a
-- falsifiable factual assertion about the plant: if it proves wrong, the signer was mistaken, and
-- being mistaken is a different thing from having disregarded. The constructor's name is the
-- difference between those two positions in a witness box, and it costs nothing to get right.
--
-- `suspected_rubber_stamp` does not exist here, in telemetry, or anywhere else, ever.
--
--   applied             the control was reinstated
--   mitigated           a compensating control carries the risk. Requires req_compensating
--   mechanism_absent    the failure mode cannot arise on this plant. Requires a predicate
--   escalated           handed up; the obligation is not cleared, it is someone else's
--   accept_residual     the risk is accepted, bounded, and expires. Never over fatal ancestry
--   emergency_override  the permit proceeds and the record is loud. Always expires
--
-- Two of these six have no row at `blood_fatal` in `clearance_legal`, and one has none at
-- `blood_major`. That absence — not a flag, not a warning — is the mechanism (see 0018).

CREATE TYPE mainline.disposition_kind AS ENUM
  ('applied', 'mitigated', 'mechanism_absent', 'escalated', 'accept_residual', 'emergency_override');
