-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI25, MI11
-- I: I02
-- COUNSEL-GATED: no
-- RATIONALE: Virulence is banded from the blame closure's `max_severity` and from nothing else — never from the change's declared risk — and giving it a type of its own is what lets the clearance lattice be a composite FK on (virulence, kind) instead of a pair of strings a writer supplies.
--
-- migration:  0013_type_virulence_class
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §5.0 (verbatim) · §4 (the closure diagram) · §16 MI25
-- requires:   0002 CREATE SCHEMA mainline
-- sqlstate:   22P02 on an unknown label; P0001 from fn_check_project on a missing closure
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- THIS IS THE SCALAR THE COMPANY IS BUILT ON. Everything ancestry-conditioned in MAINLINE reads
-- `clause_blame_current.max_severity` and the virulence banded from it: every gate, every
-- clearance-lattice 23503, every drift finding, every weaken-over-blood check.
--
-- Because it is that load-bearing, the ONE rule about this type matters more than the type:
-- a column of this type that a CHECK or a composite FK reads is written by a trigger from the
-- blame closure and is RAISEd on if the closure is missing (P2, MI25). A client-supplied
-- `virulence` is overwritten, not trusted — that is conformance case CF-07, and CF-07 is the only
-- test of the claim the company is built on.
--
-- The word is "virulence", not "severity", deliberately. Severity is a property of an event.
-- Virulence is a property of what the event's blame ancestry does to a clause you are about to
-- weaken — it is transmissibility through the record, and it is a different quantity.
--
--   routine      no blood in the ancestry
--   serious      injury ancestry
--   blood_major  ancestry includes a major-injury event
--   blood_fatal  ancestry includes a fatality. Two disposition kinds have no row here at all.

CREATE TYPE mainline.virulence_class AS ENUM
  ('routine', 'serious', 'blood_major', 'blood_fatal');
