-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI13, MI15
-- I: I11
-- COUNSEL-GATED: no
-- RATIONALE: `refuted` must be a state and never a deletion — an edge that turned out to be wrong is a fact about the record's history, and removing it would destroy the evidence that the system once believed it.
--
-- migration:  0015_type_blame_state
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §5.0 (verbatim) · §5.4
-- requires:   0002 CREATE SCHEMA mainline
-- sqlstate:   22P02 on an unknown label; 23514 on inference_never_blocks
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
--   active       this edge counts. It contributes to the closure and can arm the gate
--   provisional  asserted but not yet corroborated; visible, never blocking
--   dormant      true once, superseded by a later revision of the same finding
--   refuted      shown to be wrong, ON THE RECORD, with the row still present
--
-- `refuted` rather than `DELETE` is the same discipline as Class E's "never silently fix": a
-- corrected checkpoint is a new entry recording the defect, never a re-issued old one. An edge
-- that was believed for eight months and then refuted is exactly the fact a plaintiff's expert
-- will look for, and a system that erases it has manufactured its own worst exhibit — because the
-- absence is discoverable from the closure generations that referenced it.
--
-- The interaction with MI13 is the constraint that matters: `inference_never_blocks` is a CHECK
-- over (basis, state) — an `inferred_semantic` edge may hold `provisional`, `dormant` or
-- `refuted`, and may never hold `active`. Two types, one CHECK, no service code.

CREATE TYPE mainline.blame_state AS ENUM
  ('active', 'provisional', 'dormant', 'refuted');
