-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI23
-- I: I12
-- COUNSEL-GATED: no
-- RATIONALE: A lesson that reaches a sister site and is declined must leave a row saying so, because "we told them and they said no" and "we never told them" are the two answers to the same discovery question and only one of them is survivable.
--
-- migration:  0016_type_prop_state
-- band:       0001-0023 · dm-foundation
-- statements: 1
-- source:     ARCHITECTURE.md §5.0 (verbatim) · §5.9 (fleet propagation)
-- requires:   0002 CREATE SCHEMA mainline
-- sqlstate:   22P02 on an unknown label; 23514 on only_tightenings_travel
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
--   proposed        the lesson has been offered to this site
--   already_present the receiving site's control was already at least this tight
--   conflicted      it collides with a local control; a human must resolve it
--   adopted         taken up
--   declined        refused, by a named person, with a reason
--   revoked         withdrawn by the originating site
--
-- MI23 — ONLY TIGHTENINGS TRAVEL — is the constraint this type serves, and it is the one fleet
-- feature that is a safety property rather than a convenience. Propagating a weakening across a
-- fleet is how one site's local risk acceptance silently becomes six sites' standard. A tightening
-- that propagates badly costs money; a weakening that propagates badly costs a person. The CHECK
-- only travels in one direction, and there is no configuration flag that reverses it.
--
-- `declined` is the label that earns its keep. A fleet propagation model with no way to record a
-- refusal quietly converts every non-adoption into an absence of evidence, which is the shape of
-- record that turns a corporate defendant's own system into the plaintiff's exhibit.

CREATE TYPE mainline.prop_state AS ENUM
  ('proposed', 'already_present', 'conflicted', 'adopted', 'declined', 'revoked');
