-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI17
-- I: I13
-- COUNSEL-GATED: no
-- RATIONALE: The trigram index is the one construct in this band whose syntax CockroachDB does not document for the inline CREATE TABLE form, and DR-3 already accepts that it may be rejected on v26.2 — so it ships as its own statement, where its failure costs a fuzzy-match convenience index instead of taking mainline.clause_version down with it.
--
-- migration:  0029a_clause_version_trgm
-- band:       0024-0031, 0047-0049 · dm-spine
-- statements: 1
-- source:     ARCHITECTURE.md §5.3 (`CREATE INDEX cv_trgm … USING GIN (canon_text gin_trgm_ops)`)
--             · docs/leads/datamodel.md DR-3 · ruling D7 (lower-case letter suffix for a slot
--             that needs a second statement)
-- requires:   0029 mainline.clause_version
-- projects:   nothing.
-- sqlstate:   none at write time. This is an index; it refuses nothing.
-- forward-only; no .down.sql exists at or below the protected floor (DM-14).
--
-- WHY THIS IS A SEPARATE FILE AND NOT AN INLINE INDEX (a recorded deviation from the brief).
-- DM-6 says secondary indexes are declared inline in CREATE TABLE, and every other index in this
-- band is. This one is not, for a reason that is specific and checkable:
--
--   * CockroachDB documents the operator-class form for the standalone statement —
--     `CREATE INVERTED INDEX name ON t (col opclass)` and the PostgreSQL-compatible
--     `CREATE INDEX … USING GIN (col gin_trgm_ops)`.
--   * It does NOT document an operator class inside a CREATE TABLE index definition. The parser
--     very likely accepts it, since index elements are shared grammar — but "very likely" is not
--     a thing to put in the middle of the statement that creates the spine's central table.
--   * No CockroachDB v26.2 was reachable from the machine this band was authored on, so neither
--     form could be executed to settle it.
--
-- DR-3 in docs/leads/datamodel.md already accepts the risk that `gin_trgm_ops` is rejected on
-- v26.2 and names dm-spine as an owner. Isolating it here makes the accepted degradation a
-- ONE-FILE DELETION rather than a redesign of 0029: the lexical channel is explicit BM25 tables
-- (mainline.lex_posting, lex_stats, lex_doclen — band 0040-0046), and fuzzy matching degrades to
-- application-side computation. Nothing beneath a gate depends on this index.
--
-- WHAT IT IS FOR. Trigram similarity over `canon_text` supports two things, neither of which is a
-- refusal: near-duplicate detection when the identity matcher is deciding whether a reworded
-- clause is the same obligation (alongside the MinHash bands in 0030), and the console's
-- free-text search over clause bodies. Both are RECALL aids. If this index is absent they are
-- slower, and the residue machinery in 0049 conserves the matcher's failures either way — a
-- missed match becomes an undispositioned residue row, which raises a gate rather than lowering
-- one. That asymmetry is what makes it safe to treat this index as optional.
--
-- The PostgreSQL-compatible `USING GIN` spelling is used rather than `CREATE INVERTED INDEX`
-- because §5.3 prints it that way and because CockroachDB treats GIN and GIST as synonymous for
-- trigram indexes; if the parser rejects this spelling on v26.2, the equivalent
-- `CREATE INVERTED INDEX cv_trgm ON mainline.clause_version (canon_text gin_trgm_ops)` is the
-- documented alternative and is a one-line edit to this file.
--
-- No STORING clause: rule 9 of the domain constraints — inverted column last, no STORING.
--
-- UNVERIFIED ON THIS MACHINE: no CockroachDB v26.2 was reachable when this band was authored, so
-- this statement has not been executed. tests/integration/schema/test_mi_spine.py applies it and
-- records a PLATFORM FINDING rather than a silent skip if v26.2 refuses it.

CREATE INDEX cv_trgm ON mainline.clause_version USING GIN (canon_text gin_trgm_ops);
