-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: FSL-1.1-ALv2
--
-- MI: MI17, MI25
-- I: I02
-- COUNSEL-GATED: no
-- RATIONALE: The weld is the mechanism: without this trigger `mainline_meas.recall_candidate.severity` is an inserter-supplied number that sets its own evidence threshold, and `pg_get_triggerdef()` snapshots this definition into the custody ledger so that removing it is an act with a record rather than a quiet edit.
--
-- migration:  0139_trg_candidate_project
-- band:       0136-0139z · recall · AUTHORED, allocated by
--             verticals/mainline/db/migrations.allocation.toml (MR-6 lock 1)
-- domain:     recall
-- statements: 1
-- source:     ARCHITECTURE.md §5.7 ("PROJECTED from event.severity_gate (S10)") · §5.11
-- requires:   0110 mainline.fn_candidate_project · 0082 mainline_meas.recall_candidate
-- sqlstate:   P0001 (raised by the function, on an event that does not exist)
-- forward-only; no .down.sql exists at or below the protected floor (DM-14). Under MR-5 there
--             is no .up.sql either: the suffix named a counterpart that is illegal by
--             construction.
--
-- ── THE FUNCTION MOVED OUT OF THIS FILE (migration reconciliation, 2026-08-08) ────────────────
-- This file used to carry `CREATE FUNCTION mainline.fn_candidate_project()` as its first
-- statement, on the stated grounds that recall owned no free function number. It owned two:
-- `migrations.allocation.toml` grants recall `0110`-`0114z`, and `0110` was empty. The function
-- now lives in `0110_fn_candidate_project.sql`, which is where §18 puts functions — created
-- before the `0120`-`0139` trigger stratum rather than inside it — and that file's header
-- carries the full argument, including the two ways the old shape was wrong. Nothing about the
-- mechanism changed: same function name, same body, same trigger name, same SQLSTATE.
--
-- BEFORE INSERT, because the point is to REWRITE the row rather than to refuse it — except when
-- the event does not exist at all, which cannot be repaired by rewriting and is therefore the
-- one case that RAISEs.
--
-- The trigger NAME is the mechanism's public surface: the unwelding suite and
-- `pg_get_triggerdef()`'s attestation into `mainline_ops.schema_attestation` both address it by
-- name, so `candidate_project` is stable across this reconciliation and across any future one.
--
-- REFUSAL DEPTH, honestly: 1. With this trigger dropped, `severity` becomes an inserter-supplied
-- number again and only `candidate_sev_range` (0082) still constrains it — to 0..5, which is
-- exactly the range the attack in `0110`'s header operates inside. What survives the unweld is
-- the FK on `run_id` and nothing about severity. The suite asserts that rather than implying a
-- redundancy that is not there.

CREATE TRIGGER candidate_project BEFORE INSERT ON mainline_meas.recall_candidate
  FOR EACH ROW EXECUTE FUNCTION mainline.fn_candidate_project();
