# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: Apache-2.0
"""Deterministic port of ``cyberphone/json-canonicalization/testdata/numgen.go``.

The official ES6 number vector is ``es6testfile100m.txt`` — 100 million lines, 4.0 GB
uncompressed. Committing it is absurd and downloading it in CI makes the ES6 conformance
claim depend on a network. Neither is necessary, because upstream publishes the
**SHA-256 of the first N lines** of the deterministically generated file:

===========  ==================================================================  ==========
lines        sha256 of the generated bytes                                        size
===========  ==================================================================  ==========
1 000        ``be18b62b6f69cdab33a7e0dae0d9cfa869fda80ddc712221570f9f40a5878687``  37 967
10 000       ``b9f7a8e75ef22a835685a52ccba7f7d6bdc99e34b010992cbc5864cd12be6892``  399 022
100 000      ``22776e6d4b49fa294a0d0f349268e5c28808fe7e0cb2bcbe28f63894e494d4c7``  4 031 728
1 000 000    ``49415fee2c56c77864931bd3624faad425c3c577d6d74e89a83bc725506dad16``  40 357 417
===========  ==================================================================  ==========

Each line is ``<lowercase hex of the IEEE-754 bits, unpadded>,<expected serialisation>\\n``.
The *expected serialisation* half is produced here by
:func:`trappoint_jcs.canon_v1.es6_number`, so reproducing the published hash is a
statement about **our** serialiser, not about our copy of the file: if a single one of
those thousands of numbers formatted differently, the digest would not match.

``float_sequence`` reproduces the generator exactly — 168 static bit patterns, then 2000
consecutive bit patterns from the smallest normal double upward, then an endless SHA-256
chain reinterpreted as little-endian doubles with zero, NaN and the infinities skipped.
"""

from __future__ import annotations

import hashlib
import math
import struct
from collections.abc import Callable, Iterator

__all__ = ["PUBLISHED_DIGESTS", "float_sequence", "generate_lines"]

#: ``lines -> (sha256 hex of the generated file prefix, size in bytes)``, from the upstream
#: ``testdata/README.md`` table. These are the only numbers in this repository that were
#: copied from a third party and are treated as ground truth.
PUBLISHED_DIGESTS: dict[int, tuple[str, int]] = {
    1_000: ("be18b62b6f69cdab33a7e0dae0d9cfa869fda80ddc712221570f9f40a5878687", 37_967),
    10_000: ("b9f7a8e75ef22a835685a52ccba7f7d6bdc99e34b010992cbc5864cd12be6892", 399_022),
    100_000: ("22776e6d4b49fa294a0d0f349268e5c28808fe7e0cb2bcbe28f63894e494d4c7", 4_031_728),
    1_000_000: ("49415fee2c56c77864931bd3624faad425c3c577d6d74e89a83bc725506dad16", 40_357_417),
}

_STATIC: tuple[int, ...] = (
    0x0000000000000000, 0x8000000000000000, 0x0000000000000001, 0x8000000000000001,
    0xC46696695DBD1CC3, 0xC43211EDE4974A35, 0xC3FCE97CA0F21056, 0xC3C7213080C1A6AC,
    0xC39280F39A348556, 0xC35D9B1F5D20D557, 0xC327AF4C4A80AAAC, 0xC2F2F2A36ECD5556,
    0xC2BE51057E155558, 0xC28840D131AAAAAC, 0xC253670DC1555557, 0xC21F0B4935555557,
    0xC1E8D5D42AAAAAAC, 0xC1B3DE4355555556, 0xC17FCA0555555556, 0xC1496E6AAAAAAAAB,
    0xC114585555555555, 0xC0E046AAAAAAAAAB, 0xC0AA0AAAAAAAAAAA, 0xC074D55555555555,
    0xC040AAAAAAAAAAAB, 0xC00AAAAAAAAAAAAB, 0xBFD5555555555555, 0xBFA1111111111111,
    0xBF6B4E81B4E81B4F, 0xBF35D867C3ECE2A5, 0xBF0179EC9CBD821E, 0xBECBF647612F3696,
    0xBE965E9F80F29212, 0xBE61E54C672874DB, 0xBE2CA213D840BAF8, 0xBDF6E80FE033C8C6,
    0xBDC2533FE68FD3D2, 0xBD8D51FFD74C861C, 0xBD5774CCAC3D3817, 0xBD22C3D6F030F9AC,
    0xBCEE0624B3818F79, 0xBCB804EA293472C7, 0xBC833721BA905BD3, 0xBC4EBE9C5DB3C61E,
    0xBC18987D17C304E5, 0xBBE3AD30DFCF371D, 0xBBAF7B816618582F, 0xBB792F9AB81379BF,
    0xBB442615600F9499, 0xBB101E77800C76E1, 0xBAD9CA58CCE0BE35, 0xBAA4A1E0A3E6FE90,
    0xBA708180831F320D, 0xBA3A68CD9E985016, 0x446696695DBD1CC3, 0x443211EDE4974A35,
    0x43FCE97CA0F21056, 0x43C7213080C1A6AC, 0x439280F39A348556, 0x435D9B1F5D20D557,
    0x4327AF4C4A80AAAC, 0x42F2F2A36ECD5556, 0x42BE51057E155558, 0x428840D131AAAAAC,
    0x4253670DC1555557, 0x421F0B4935555557, 0x41E8D5D42AAAAAAC, 0x41B3DE4355555556,
    0x417FCA0555555556, 0x41496E6AAAAAAAAB, 0x4114585555555555, 0x40E046AAAAAAAAAB,
    0x40AA0AAAAAAAAAAA, 0x4074D55555555555, 0x4040AAAAAAAAAAAB, 0x400AAAAAAAAAAAAB,
    0x3FD5555555555555, 0x3FA1111111111111, 0x3F6B4E81B4E81B4F, 0x3F35D867C3ECE2A5,
    0x3F0179EC9CBD821E, 0x3ECBF647612F3696, 0x3E965E9F80F29212, 0x3E61E54C672874DB,
    0x3E2CA213D840BAF8, 0x3DF6E80FE033C8C6, 0x3DC2533FE68FD3D2, 0x3D8D51FFD74C861C,
    0x3D5774CCAC3D3817, 0x3D22C3D6F030F9AC, 0x3CEE0624B3818F79, 0x3CB804EA293472C7,
    0x3C833721BA905BD3, 0x3C4EBE9C5DB3C61E, 0x3C18987D17C304E5, 0x3BE3AD30DFCF371D,
    0x3BAF7B816618582F, 0x3B792F9AB81379BF, 0x3B442615600F9499, 0x3B101E77800C76E1,
    0x3AD9CA58CCE0BE35, 0x3AA4A1E0A3E6FE90, 0x3A708180831F320D, 0x3A3A68CD9E985016,
    0x4024000000000000, 0x4014000000000000, 0x3FE0000000000000, 0x3FA999999999999A,
    0x3F747AE147AE147B, 0x3F40624DD2F1A9FC, 0x3F0A36E2EB1C432D, 0x3ED4F8B588E368F1,
    0x3EA0C6F7A0B5ED8D, 0x3E6AD7F29ABCAF48, 0x3E35798EE2308C3A, 0x3ED539223589FA95,
    0x3ED4FF26CD5A7781, 0x3ED4F95A762283FF, 0x3ED4F8C60703520C, 0x3ED4F8B72F19CD0D,
    0x3ED4F8B5B31C0C8D, 0x3ED4F8B58D1C461A, 0x3ED4F8B5894F7F0E, 0x3ED4F8B588EE37F3,
    0x3ED4F8B588E47DA4, 0x3ED4F8B588E3849C, 0x3ED4F8B588E36BB5, 0x3ED4F8B588E36937,
    0x3ED4F8B588E368F8, 0x3ED4F8B588E368F1, 0x3FF0000000000000, 0xBFF0000000000000,
    0xBFEFFFFFFFFFFFFA, 0xBFEFFFFFFFFFFFFB, 0x3FEFFFFFFFFFFFFA, 0x3FEFFFFFFFFFFFFB,
    0x3FEFFFFFFFFFFFFC, 0x3FEFFFFFFFFFFFFE, 0xBFEFFFFFFFFFFFFF, 0xBFEFFFFFFFFFFFFF,
    0x3FEFFFFFFFFFFFFF, 0x3FEFFFFFFFFFFFFF, 0x3FD3333333333332, 0x3FD3333333333333,
    0x3FD3333333333334, 0x0010000000000000, 0x000FFFFFFFFFFFFD, 0x000FFFFFFFFFFFFF,
    0x7FEFFFFFFFFFFFFF, 0xFFEFFFFFFFFFFFFF, 0x4340000000000000, 0xC340000000000000,
    0x4430000000000000, 0x44B52D02C7E14AF5, 0x44B52D02C7E14AF6, 0x44B52D02C7E14AF7,
    0x444B1AE4D6E2EF4E, 0x444B1AE4D6E2EF4F, 0x444B1AE4D6E2EF50, 0x3EB0C6F7A0B5ED8C,
    0x3EB0C6F7A0B5ED8D, 0x41B3DE4355555553, 0x41B3DE4355555554, 0x41B3DE4355555555,
    0x41B3DE4355555556, 0x41B3DE4355555557, 0xBECBF647612F3696, 0x43143FF3C1CB0959,
)

#: 2000 consecutive bit patterns starting at the smallest positive normal double.
_NUM_SERIAL = 2000
_SMALLEST_NORMAL_BITS = 0x0010000000000000


def _bits_to_float(bits: int) -> float:
    return struct.unpack("<d", struct.pack("<Q", bits))[0]


def _float_to_bits(value: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", value))[0]


def float_sequence() -> Iterator[float]:
    """Yield the upstream sequence of doubles, forever."""
    index = 0
    block = bytes(32)
    data = b""
    while True:
        if index < len(_STATIC):
            value = _bits_to_float(_STATIC[index])
        elif index < len(_STATIC) + _NUM_SERIAL:
            value = _bits_to_float(_SMALLEST_NORMAL_BITS + (index - len(_STATIC)))
        else:
            value = 0.0
            while value == 0.0 or math.isnan(value) or math.isinf(value):
                if not data:
                    block = hashlib.sha256(block).digest()
                    data = block
                value = _bits_to_float(int.from_bytes(data[:8], "little"))
                data = data[8:]
        index += 1
        yield value


def generate_lines(count: int, serialise: Callable[[float], str]) -> Iterator[bytes]:
    """Yield ``count`` lines of the ES6 test file, formatting numbers with *serialise*.

    *serialise* is passed in rather than imported so this module stays usable as a plain
    oracle: the test hands it :func:`trappoint_jcs.canon_v1.es6_number`, and any
    third-party implementation can be checked the same way.
    """
    sequence = float_sequence()
    for _ in range(count):
        value = next(sequence)
        yield f"{_float_to_bits(value):x},{serialise(value)}\n".encode()
