# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: LicenseRef-FSL-1.1-ALv2
"""Fixtures and isolation for the cue-synthesis suite.

The suite must pass with **no AWS credentials and no network**, and the guarantee is
enforced rather than asserted in prose: a lazily-acquired boto3 session that timed out and
fell back to something plausible would leave the suite green while the offline guarantee
quietly died.

Cassettes live under ``tests/unit/recall_cue/cassettes`` — beside the tests that use them,
not in the shared provider fixture tree — because they are keyed on *this* package's prompt
digest and are regenerated by *this* package's ``make_cue_cassettes.py``.
"""

from __future__ import annotations

import socket
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parents[2]
PACKAGE_SRC = REPO_ROOT / "verticals" / "mainline" / "packages" / "mainline-recall-agent" / "src"
CASSETTE_ROOT = TESTS_DIR / "cassettes"

for path in (str(PACKAGE_SRC), str(TESTS_DIR)):
    if path not in sys.path:  # pragma: no cover - import-time bootstrap
        sys.path.insert(0, path)

_OWNED_ENV = (
    "MAINLINE_RECALL_PROVIDER",
    "MAINLINE_RECALL_CASSETTE_MODE",
    "MAINLINE_RECALL_ALLOW_NETWORK",
    "MAINLINE_RECALL_CASSETTE_DIR",
    "AWS_REGION",
)


class NetworkAccessInTest(RuntimeError):
    """Raised when a test in this directory tries to open a socket."""


@pytest.fixture(autouse=True)
def no_network(monkeypatch: pytest.MonkeyPatch) -> None:
    """Cue synthesis is a model call; this suite proves it can be replayed without one."""

    def _refuse(*args: Any, **kwargs: Any) -> Any:
        raise NetworkAccessInTest(
            "a test in tests/unit/recall_cue attempted an outbound connection. This suite "
            "must pass with no credentials and no network: use a cassette or a scripted "
            "transport."
        )

    monkeypatch.setattr(socket.socket, "connect", _refuse, raising=True)
    monkeypatch.setattr(socket.socket, "connect_ex", _refuse, raising=True)
    monkeypatch.setattr(socket, "create_connection", _refuse, raising=True)


@pytest.fixture(autouse=True)
def isolated_env(monkeypatch: pytest.MonkeyPatch) -> None:
    for name in _OWNED_ENV:
        monkeypatch.delenv(name, raising=False)
    monkeypatch.setenv("MAINLINE_RECALL_CASSETTE_DIR", str(CASSETTE_ROOT))
    monkeypatch.setenv("AWS_REGION", "ap-southeast-2")


@pytest.fixture
def cassette_root() -> Path:
    return CASSETTE_ROOT


@pytest.fixture
def replay_judge() -> Callable[[], Any]:
    """A judge that replays the committed cue cassettes.

    Returns a factory rather than an instance: several tests need a *fresh* judge so that
    ``call_count`` measures one scenario rather than the whole module.
    """
    from fixtures import CASSETTE_MODEL
    from mainline_recall_agent.cue.prompts import PROMPT_VERSION
    from mainline_recall_agent.providers.cassette import CassetteJudgeTransport, CassetteStore
    from mainline_recall_agent.providers.judge import BedrockClaudeJudge

    def factory() -> Any:
        return BedrockClaudeJudge(
            resolved_model=CASSETTE_MODEL,
            transport=CassetteJudgeTransport(CassetteStore(CASSETTE_ROOT)),
            prompt_version=PROMPT_VERSION,
            max_tokens=4096,
        )

    return factory
