# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: Apache-2.0
"""The transaction programs the interleaving scheduler runs.

Two, and they are the two halves of anomaly **A1**: a merge that re-derives the open
obligation count, and a materialisation that creates one. Run sequentially either order
is safe; run interleaved, a gate that trusted its own counter has a window.

Kept out of :mod:`~trappoint_model.adapter` on purpose. The adapter drives *sequential*
histories on one autocommit connection and each of its methods is one logical step; a
scheduler program is a list of statements that must be handed out one at a time across
threads. Sharing one function between the two shapes would mean neither was the natural
one.

The SQL is the same SQL the adapter issues, and ``tests/test_programs_match_adapter.py``
is not needed to say so — both call the same procedure and the same table, and the
conformance corpus is what pins the statement text to the spec. What matters here is that
nothing in this module *decides*: every program is a fixed list, so which refusal an
interleaving produces is entirely the database's opinion.
"""

from __future__ import annotations

import uuid

from .refschema import SCHEMA, Fixture
from .scheduler import Statement

__all__ = ["materialise_program", "merge_program"]


def merge_program(subject: uuid.UUID, fixture: Fixture) -> list[Statement]:
    """One statement: ``CALL merge_permit(...)``.

    A single statement is not a simplification — it is the product's own shape. §5.3 puts
    the whole gate transaction in one server-side procedure precisely so a client crash
    cannot leave the transition half-performed, so an interleaving that split it into
    seven client statements would be exercising a client nobody ships.
    """
    return [
        Statement(
            label="merge",
            sql=f"CALL {SCHEMA}.merge_permit(%s, %s, %s, 'service', %s, %s, 1::INT2, %s)",
            params=(
                subject,
                uuid.uuid4().bytes + uuid.uuid4().bytes,
                fixture.signer_sub,
                "{}",
                b"\x00",
                b"\x00" * 32,
            ),
        )
    ]


def materialise_program(
    subject: uuid.UUID,
    check_id: uuid.UUID,
    clause_uuid: uuid.UUID,
    commit_id: bytes,
    fixture: Fixture,
) -> list[Statement]:
    """One statement: a new obligation on *subject*.

    The clause version and its blame closure are seeded **outside** the transaction, by
    the caller, because they are the authority source rather than part of the race. A
    program that created its own authority row would be racing two things at once and the
    counterexample would not say which.
    """
    return [
        Statement(
            label="materialise",
            sql=(
                f"INSERT INTO {SCHEMA}.blocking_check (check_id, subject_kind, permit_id, "  # noqa: S608
                "site_id, clause_uuid, commit_id, origin, severity, virulence, closure_gen, "
                "evidence_summary) "
                "VALUES (%s, 'permit', %s, %s, %s, %s, 'blame_ancestry', 0, 'routine', 99, %s)"
            ),
            params=(
                check_id,
                subject,
                fixture.site_id,
                clause_uuid,
                commit_id,
                "generated by the interleaving scheduler",
            ),
        )
    ]
