-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: Apache-2.0
--
-- TRAPPOINT_REF · 0006h_role_reader.sql
-- CREATE ROLE tref_reader — the reader slot
--
-- MI: MI01
-- I: I01
-- COUNSEL-GATED: no
-- RATIONALE: read-only across business records and measurement; no write path anywhere. IF
--            NOT EXISTS because a role is cluster state, not schema state: a restore does
--            not carry it, two verticals on one cluster legitimately share the agent roles,
--            and re-asserting one must never be an error.
--
-- @rendered-by  trappoint render
-- @template     packages/trappoint-sql/templates/0006_roles.sql.j2
-- @binding      packages/trappoint-sql/refvertical/vertical.toml
-- DO NOT EDIT. `trappoint render --check` is a zero-diff assertion in CI, so a
-- hand edit here is a red build, not a silent divergence.
--
-- Slot         reader
-- Name         tref_reader   (overridable in [roles] of the binding)

CREATE ROLE IF NOT EXISTS tref_reader;
