#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: FSL-1.1-ALv2
"""Regenerate ``VO-CUT.diff`` from ``VO-DRAFT.md`` and ``VO.md``.

    python verticals/mainline/demo/script/make_cut_diff.py            # write it
    python verticals/mainline/demo/script/make_cut_diff.py --check    # assert it is current

demo-engineering.md §5 says: draft, read aloud against a stopwatch, cut 20 %. A
line in a README saying "we cut twenty per cent" is not evidence that anything was
cut, so the cut is a **diff**, and the percentage in that diff's header is
**measured here**, never typed. ``--check`` makes staleness a red build rather
than an inaccuracy nobody notices.

Only spoken words are counted: the timecode markers (``[0:00]``, ``[0:33·hold]``)
and the prose header of the draft are scaffolding and are excluded, because a cut
that shrinks the commentary and not the script is not a cut.
"""

# ruff: noqa: T201 - this file is a CLI entry point and stdout IS its interface.
# ruff.toml exempts **/cli.py for exactly this reason; these scripts are the same
# shape under a different name, and a report nobody can read is not a control.

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DRAFT = HERE / "VO-DRAFT.md"
LOCKED = HERE / "VO.md"
OUT = HERE / "VO-CUT.diff"

CUE = re.compile(r"^\[(\d+:\d\d)(·hold)?\]\s*(.*)$")


def spoken_lines(path: Path) -> list[tuple[str, str]]:
    """Return ``(timecode, line)`` for every cued line, in order."""
    out: list[tuple[str, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        match = CUE.match(raw.strip())
        if match:
            out.append((match.group(1), match.group(3).strip()))
    return out


def words(lines: list[tuple[str, str]]) -> int:
    return sum(len(line.split()) for _, line in lines)


def render() -> str:
    draft = spoken_lines(DRAFT)
    locked = spoken_lines(LOCKED)
    if not draft or not locked:
        raise SystemExit("VO-DRAFT.md or VO.md carries no cued lines — nothing to diff")

    draft_words = words(draft)
    locked_words = words(locked)
    removed = draft_words - locked_words
    pct = (removed / draft_words * 100) if draft_words else 0.0

    body = difflib.unified_diff(
        [f"[{t}] {line}" for t, line in draft],
        [f"[{t}] {line}" for t, line in locked],
        fromfile="VO-DRAFT.md",
        tofile="VO.md",
        lineterm="",
        n=0,
    )
    header = [
        "# SPDX-FileCopyrightText: 2026 MAINLINE contributors",
        "# SPDX-License-Identifier: FSL-1.1-ALv2",
        "#",
        "# The 20 % cut, as a diff. GENERATED by make_cut_diff.py — do not hand-edit.",
        "#",
        f"#   draft spoken words   {draft_words}",
        f"#   locked spoken words  {locked_words}",
        f"#   removed              {removed}",
        f"#   reduction            {pct:.1f} %",
        "#",
        "# Every removed word is a qualifier, a restatement of something the screen is",
        "# already showing, or a sentence explaining a shot instead of letting it land.",
        "# Nothing removed here was a claim; the claims are in every line that survived.",
        "#",
    ]
    return "\n".join(header + list(body)) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if VO-CUT.diff is stale")
    args = parser.parse_args(argv)

    generated = render()
    if args.check:
        if not OUT.is_file():
            print("VO-CUT.diff does not exist — the cut is unrecorded")
            return 1
        if OUT.read_text(encoding="utf-8") != generated:
            print("VO-CUT.diff is stale — run make_cut_diff.py")
            return 1
        print("VO-CUT.diff is current")
        return 0

    OUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
