-- SPDX-FileCopyrightText: 2026 MAINLINE contributors
-- SPDX-License-Identifier: Apache-2.0
--
-- THE SELF-ATTESTING GATE. Generated by tests/test_gate_source_snapshot.py from
-- the LIVE cluster, never from the repository. A diff in this file is the
-- sentence 'the merge gate changed', and it is the only place that sentence is
-- guaranteed to appear in a review.
--
-- snapshot strength: STRONG (pg_get_functiondef + pg_get_triggerdef)

-- ── FUNCTION fn_check_materialised ───────────────
CREATE FUNCTION trappoint_ref.fn_check_materialised()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_state trappoint_ref.subject_state;
	BEGIN
	IF (new).permit_id IS NOT NULL THEN
		SELECT t.state FROM trappoint_ref.permit AS t WHERE t.permit_id = (new).permit_id FOR UPDATE INTO v_state;
		IF v_state IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no permit row for this blocking check \U00002014 the gate has no subject to close';
	END IF;
		IF v_state = 'merged' THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: precursor arrived after issue \U00002014 use the post-issue recall path';
	END IF;
		UPDATE trappoint_ref.permit SET open_blocking = open_blocking + 1, gate_epoch = gate_epoch + 1 WHERE permit_id = (new).permit_id;
	ELSIF (new).cr_id IS NOT NULL THEN
		SELECT t.state FROM trappoint_ref.change_request AS t WHERE t.cr_id = (new).cr_id FOR UPDATE INTO v_state;
		IF v_state IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no change_request row for this blocking check \U00002014 the gate has no subject to close';
	END IF;
		IF v_state = 'merged' THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: precursor arrived after issue \U00002014 use the post-issue recall path';
	END IF;
		UPDATE trappoint_ref.change_request SET open_blocking = open_blocking + 1, gate_epoch = gate_epoch + 1 WHERE cr_id = (new).cr_id;
	ELSE
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: a blocking check names no gated subject \U00002014 an obligation that blocks nothing is not an obligation';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_check_project ───────────────
CREATE FUNCTION trappoint_ref.fn_check_project()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_severity INT2;
	v_virulence trappoint_ref.virulence_class;
	v_closure_gen INT8;
	BEGIN
	SELECT c.max_severity, c.virulence, c.closure_gen FROM trappoint_ref.clause_blame_current AS c WHERE (c.clause_uuid = (new).clause_uuid) AND (c.as_of_commit = (new).commit_id) INTO v_severity, v_virulence, v_closure_gen;
	IF v_severity IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no blame closure for this clause version \U00002014 cannot arm a check';
	END IF;
	new.severity := v_severity;
	new.virulence := v_virulence;
	new.closure_gen := v_closure_gen;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_closure_guard ───────────────
CREATE FUNCTION trappoint_ref.fn_closure_guard()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_prev_severity INT2;
	v_prev_gen INT8;
	v_revisions INT8;
	v_site_code STRING;
	BEGIN
	SELECT c.max_severity, c.closure_gen FROM trappoint_ref.clause_blame_closure AS c WHERE (c.clause_uuid = (new).clause_uuid) AND (c.as_of_commit = (new).as_of_commit) ORDER BY c.closure_gen DESC LIMIT 1 INTO v_prev_severity, v_prev_gen;
	IF (v_prev_gen IS NULL) AND ((new).closure_gen != 0) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: the first closure generation for a clause version must be zero';
	END IF;
	IF (v_prev_gen IS NOT NULL) AND ((new).closure_gen != (v_prev_gen + 1)) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: closure generations must be dense and monotone';
	END IF;
	IF (v_prev_severity IS NOT NULL) AND ((new).max_severity < v_prev_severity) THEN
		SELECT count(*) FROM trappoint_ref.event_severity_revision AS r WHERE r.at >= transaction_timestamp() INTO v_revisions;
		IF v_revisions = 0 THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: closure severity may not decrease without a signed severity revision';
	END IF;
	END IF;
	SELECT st.site_code FROM trappoint_ref.site AS st WHERE st.site_id = (new).site_id INTO v_site_code;
	IF v_site_code IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no site row for this closure \U00002014 the ledger partition key has no source';
	END IF;
	INSERT INTO trappoint_ref.ledger_intake(site_code, entry_kind, subject_id, actor, actor_kind, payload, canon_bytes, payload_ver, leaf_hash, hlc) VALUES (v_site_code, 'closure', (new).clause_uuid, (new).computed_by, 'service', jsonb_build_object('clause_uuid', (new).clause_uuid, 'as_of_commit', encode((new).as_of_commit, 'hex'), 'closure_gen', (new).closure_gen, 'max_severity', (new).max_severity, 'ancestor_count', (new).ancestor_count, 'truncated', (new).truncated), decode('00', 'hex'), 1, decode(repeat('0', 64), 'hex'), cluster_logical_timestamp());
	RETURN new;
	END;
$$
-- ── FUNCTION fn_cr_event_chain ───────────────
CREATE FUNCTION trappoint_ref.fn_cr_event_chain()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_existing INT8;
	v_expected BYTES;
	BEGIN
	IF (new).seq = 0 THEN
		RETURN new;
	END IF;
	SELECT count(*) FROM trappoint_ref.cr_event AS e0 WHERE e0.cr_id = (new).cr_id INTO v_existing;
	IF v_existing = 0 THEN
		RETURN new;
	END IF;
	SELECT e.chain_digest FROM trappoint_ref.cr_event AS e WHERE (e.cr_id = (new).cr_id) AND (e.seq = (new).prev_seq) INTO v_expected;
	IF v_expected IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: no predecessor event for the declared prev_seq';
	END IF;
	IF v_expected IS DISTINCT FROM (new).prev_digest THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: prev_digest does not match the predecessor chain digest';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_cr_merge_gate ───────────────
CREATE FUNCTION trappoint_ref.fn_cr_merge_gate()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_subject UUID;
	v_projected INT8;
	v_derived INT8;
	v_unbacked INT8;
	BEGIN
	v_subject := (new).cr_id;
	v_projected := (new).open_blocking;
	SELECT count(*) FROM trappoint_ref.blocking_check AS bc WHERE (bc.cr_id = v_subject) AND (NOT EXISTS (SELECT 1 FROM trappoint_ref.disposition AS d WHERE ((d.check_id = bc.check_id) AND (d.retracted_by IS NULL)) AND ((d.expires_at IS NULL) OR (d.expires_at > now())))) INTO v_derived;
	IF (v_derived != 0) AND (v_projected = 0) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = (('TRAPPOINT_REF: merge refused by trappoint_ref.fn_cr_merge_gate' || e' \U00002014 re-derived open obligation count is ') || v_derived::STRING) || ' while the projected counter reads zero';
	END IF;
	SELECT count(*) FROM trappoint_ref.cr_clause AS cited WHERE (cited.cr_id = v_subject) AND (NOT EXISTS (SELECT 1 FROM trappoint_ref.clause_blame_current AS auth WHERE (auth.clause_uuid = cited.clause_uuid) AND (auth.as_of_commit = cited.commit_id))) INTO v_unbacked;
	IF v_unbacked != 0 THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = (('TRAPPOINT_REF: merge refused by trappoint_ref.fn_cr_merge_gate' || e' \U00002014 no authority-source row for ') || v_unbacked::STRING) || ' cited clause version(s)';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_disposition_close ───────────────
CREATE FUNCTION trappoint_ref.fn_disposition_close()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	BEGIN
	IF (new).permit_id IS NOT NULL THEN
		UPDATE trappoint_ref.permit SET open_blocking = open_blocking - 1, unmet_floor_count = unmet_floor_count + (NOT (new).reading_floor_met)::INT8, countersigned_count = countersigned_count + ((new).countersigner_credential_id IS NOT NULL)::INT8 WHERE permit_id = (new).permit_id;
	ELSIF (new).cr_id IS NOT NULL THEN
		UPDATE trappoint_ref.change_request SET open_blocking = open_blocking - 1 WHERE cr_id = (new).cr_id;
	ELSE
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: a disposition names no gated subject \U00002014 nothing to close';
	END IF;
	IF (new).kind = 'emergency_override' THEN
		INSERT INTO trappoint_ref.override_ledger(site_id, signer_sub, subject_kind, permit_id, cr_id, disposition_id) VALUES ((new).site_id, (new).signer_sub, (new).subject_kind, (new).permit_id, (new).cr_id, (new).disposition_id);
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_disposition_project ───────────────
CREATE FUNCTION trappoint_ref.fn_disposition_project()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_subject_kind STRING;
	v_permit_id UUID;
	v_cr_id UUID;
	v_site_id UUID;
	v_ck_clause_uuid UUID;
	v_ck_commit_id BYTES;
	v_severity INT2;
	v_virulence trappoint_ref.virulence_class;
	v_closure_gen INT8;
	v_req_compensating BOOL;
	v_req_second_signer BOOL;
	v_req_foreign_org BOOL;
	v_req_predicate BOOL;
	v_req_reassert BOOL;
	v_min_signer_rank INT2;
	v_max_ttl_hours INT4;
	v_signer_rank INT2;
	v_signer_org STRING;
	v_competency_sha256 BYTES;
	v_competency_source_id UUID;
	v_competency_snapshot JSONB;
	v_co_rank INT2;
	v_co_org STRING;
	v_issued_at TIMESTAMPTZ;
	v_expires_at TIMESTAMPTZ;
	v_tokens INT8;
	v_tau0 FLOAT8;
	v_rho FLOAT8;
	v_anchors INT4;
	v_overrides INT8;
	v_deliberation INT8;
	BEGIN
	SELECT bc.subject_kind, bc.permit_id, bc.cr_id, bc.site_id, bc.clause_uuid, bc.commit_id FROM trappoint_ref.blocking_check AS bc WHERE bc.check_id = (new).check_id INTO v_subject_kind, v_permit_id, v_cr_id, v_site_id, v_ck_clause_uuid, v_ck_commit_id;
	IF v_subject_kind IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no such blocking check \U00002014 a disposition cannot be filed against an obligation that does not exist';
	END IF;
	SELECT c.max_severity, c.virulence, c.closure_gen FROM trappoint_ref.clause_blame_current AS c WHERE (c.clause_uuid = v_ck_clause_uuid) AND (c.as_of_commit = v_ck_commit_id) INTO v_severity, v_virulence, v_closure_gen;
	IF v_severity IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: blame closure absent \U00002014 a disposition cannot be typed';
	END IF;
	SELECT er.issued_at, er.expires_at, er.total_tokens FROM trappoint_ref.exposure_receipt AS er WHERE er.receipt_id = (new).receipt_id INTO v_issued_at, v_expires_at, v_tokens;
	IF (v_expires_at IS NULL) OR (v_expires_at <= now()) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: exposure receipt absent or expired \U00002014 re-materialise before signing';
	END IF;
	SELECT cl.req_compensating, cl.req_second_signer, cl.req_foreign_org, cl.req_predicate, cl.req_reassert, cl.min_signer_rank, cl.max_ttl_hours FROM trappoint_ref.clearance_legal AS cl WHERE (cl.virulence = v_virulence) AND (cl.kind = (new).kind) INTO v_req_compensating, v_req_second_signer, v_req_foreign_org, v_req_predicate, v_req_reassert, v_min_signer_rank, v_max_ttl_hours;
	IF v_req_compensating IS NULL THEN
		v_req_compensating := true;
		v_req_second_signer := true;
		v_req_foreign_org := true;
		v_req_predicate := true;
		v_req_reassert := true;
		v_min_signer_rank := 9;
		v_max_ttl_hours := NULL;
	END IF;
	SELECT pr.rank, pr.org, pr.competency_sha256, pr.competency_source_id, pr.competency_snapshot FROM trappoint_ref.person AS pr WHERE (pr.signer_sub = (new).signer_sub) AND (pr.effective_from <= now()) ORDER BY pr.effective_from DESC LIMIT 1 INTO v_signer_rank, v_signer_org, v_competency_sha256, v_competency_source_id, v_competency_snapshot;
	IF v_signer_rank IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no competency record for this signer \U00002014 fail closed';
	END IF;
	IF (new).countersigner_sub IS NULL THEN
		v_co_rank := NULL;
		v_co_org := NULL;
	ELSE
		SELECT pr.rank, pr.org FROM trappoint_ref.person AS pr WHERE (pr.signer_sub = (new).countersigner_sub) AND (pr.effective_from <= now()) ORDER BY pr.effective_from DESC LIMIT 1 INTO v_co_rank, v_co_org;
		IF v_co_rank IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: no competency record for this countersigner \U00002014 fail closed';
	END IF;
	END IF;
	SELECT (SELECT count(*) FROM trappoint_ref.disposition_citation AS dc WHERE (dc.disposition_id = (new).disposition_id) AND (dc.kind = 'verbatim'))::INT4, (SELECT count(*) FROM trappoint_ref.override_ledger AS ol WHERE (ol.site_id = v_site_id) AND (ol.signer_sub = (new).signer_sub))::INT8 INTO v_anchors, v_overrides;
	SELECT (rp.tau->>'tau0')::FLOAT8, (rp.tau->>'rho')::FLOAT8 FROM trappoint_ref_meas.recall_policy AS rp JOIN trappoint_ref.exposure_receipt AS er2 ON er2.policy_version = rp.policy_version WHERE er2.receipt_id = (new).receipt_id INTO v_tau0, v_rho;
	new.subject_kind := v_subject_kind;
	new.permit_id := v_permit_id;
	new.cr_id := v_cr_id;
	new.site_id := v_site_id;
	new.virulence := v_virulence;
	new.closure_gen := v_closure_gen;
	new.severity_snapshot := v_severity;
	new.req_compensating := v_req_compensating;
	new.req_second_signer := v_req_second_signer;
	new.req_foreign_org := v_req_foreign_org;
	new.req_predicate := v_req_predicate;
	new.req_reassert := v_req_reassert;
	new.min_signer_rank := v_min_signer_rank;
	new.max_ttl_hours := v_max_ttl_hours;
	new.signer_rank := v_signer_rank;
	new.signer_org := v_signer_org;
	new.competency_sha256 := v_competency_sha256;
	new.competency_source_id := v_competency_source_id;
	new.competency_snapshot := v_competency_snapshot;
	new.countersigner_rank := v_co_rank;
	new.countersigner_org := v_co_org;
	new.verbatim_anchor_count := v_anchors;
	new.prior_override_count := v_overrides;
	v_deliberation := extract('epoch', (now() - v_issued_at))::INT8;
	new.deliberation_seconds := v_deliberation;
	new.reading_floor_met := (v_deliberation::FLOAT8 >= (COALESCE(v_tau0, 5::FLOAT8) + (v_tokens::FLOAT8 / COALESCE(v_rho, 4::FLOAT8))));
	RETURN new;
	END;
$$
-- ── FUNCTION fn_disposition_retract_only ───────────────
CREATE FUNCTION trappoint_ref.fn_disposition_retract_only()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	BEGIN
	IF ((old).retracted_by IS NOT NULL) OR ((new).retracted_by IS NULL) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: dispositions are append-only except for a single retraction';
	END IF;
	IF (to_jsonb(new) - 'retracted_by') IS DISTINCT FROM (to_jsonb(old) - 'retracted_by') THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: only retracted_by may change on a disposition';
	END IF;
	IF (old).permit_id IS NOT NULL THEN
		UPDATE trappoint_ref.permit SET open_blocking = open_blocking + 1, gate_epoch = gate_epoch + 1 WHERE permit_id = (old).permit_id;
	ELSIF (old).cr_id IS NOT NULL THEN
		UPDATE trappoint_ref.change_request SET open_blocking = open_blocking + 1, gate_epoch = gate_epoch + 1 WHERE cr_id = (old).cr_id;
	ELSE
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = e'TRAPPOINT_REF: a disposition names no gated subject \U00002014 nothing to re-open';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_permit_event_chain ───────────────
CREATE FUNCTION trappoint_ref.fn_permit_event_chain()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_existing INT8;
	v_expected BYTES;
	BEGIN
	IF (new).seq = 0 THEN
		RETURN new;
	END IF;
	SELECT count(*) FROM trappoint_ref.permit_event AS e0 WHERE e0.permit_id = (new).permit_id INTO v_existing;
	IF v_existing = 0 THEN
		RETURN new;
	END IF;
	SELECT e.chain_digest FROM trappoint_ref.permit_event AS e WHERE (e.permit_id = (new).permit_id) AND (e.seq = (new).prev_seq) INTO v_expected;
	IF v_expected IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: no predecessor event for the declared prev_seq';
	END IF;
	IF v_expected IS DISTINCT FROM (new).prev_digest THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: prev_digest does not match the predecessor chain digest';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_permit_merge_gate ───────────────
CREATE FUNCTION trappoint_ref.fn_permit_merge_gate()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_subject UUID;
	v_projected INT8;
	v_derived INT8;
	v_unbacked INT8;
	BEGIN
	v_subject := (new).permit_id;
	v_projected := (new).open_blocking;
	SELECT count(*) FROM trappoint_ref.blocking_check AS bc WHERE (bc.permit_id = v_subject) AND (NOT EXISTS (SELECT 1 FROM trappoint_ref.disposition AS d WHERE ((d.check_id = bc.check_id) AND (d.retracted_by IS NULL)) AND ((d.expires_at IS NULL) OR (d.expires_at > now())))) INTO v_derived;
	IF (v_derived != 0) AND (v_projected = 0) THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = (('TRAPPOINT_REF: merge refused by trappoint_ref.fn_permit_merge_gate' || e' \U00002014 re-derived open obligation count is ') || v_derived::STRING) || ' while the projected counter reads zero';
	END IF;
	SELECT count(*) FROM trappoint_ref.permit_clause AS cited WHERE (cited.permit_id = v_subject) AND (NOT EXISTS (SELECT 1 FROM trappoint_ref.clause_blame_current AS auth WHERE (auth.clause_uuid = cited.clause_uuid) AND (auth.as_of_commit = cited.commit_id))) INTO v_unbacked;
	IF v_unbacked != 0 THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = (('TRAPPOINT_REF: merge refused by trappoint_ref.fn_permit_merge_gate' || e' \U00002014 no authority-source row for ') || v_unbacked::STRING) || ' cited clause version(s)';
	END IF;
	RETURN new;
	END;
$$
-- ── FUNCTION fn_refuse_mutation ───────────────
CREATE FUNCTION trappoint_ref.fn_refuse_mutation()
	RETURNS TRIGGER
	VOLATILE
	NOT LEAKPROOF
	CALLED ON NULL INPUT
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	BEGIN
	RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: this table is append-only; write a new row';
	END;
$$
-- ── FUNCTION merge_change_request ───────────────
CREATE PROCEDURE trappoint_ref.merge_change_request(a_subject_id UUID, a_merged_commit BYTES, a_merged_by STRING, a_actor_kind STRING, a_payload JSONB, a_canon_bytes BYTES, a_payload_ver INT2, a_leaf_hash BYTES)
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_state trappoint_ref.subject_state;
	v_head INT8;
	v_epoch INT8;
	v_open INT8;
	v_prev_digest BYTES;
	v_clearance BYTES;
	v_new_head INT8;
	BEGIN
	SELECT t.state, t.head_seq, t.gate_epoch FROM defaultdb.trappoint_ref.change_request AS t WHERE t.cr_id = a_subject_id FOR UPDATE INTO v_state, v_head, v_epoch;
	IF v_state IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: merge refused by trappoint_ref.merge_change_request':::STRING || e' \U00002014 no change_request with that identifier':::STRING;
	END IF;
	SELECT count(*) FROM (SELECT 1 FROM defaultdb.trappoint_ref.blocking_check AS bc WHERE (bc.cr_id = a_subject_id) AND (NOT EXISTS (SELECT 1 FROM defaultdb.trappoint_ref.disposition AS d WHERE ((d.check_id = bc.check_id) AND (d.retracted_by IS NULL)) AND ((d.expires_at IS NULL) OR (d.expires_at > now():::TIMESTAMPTZ)))) FOR SHARE) AS locked INTO v_open;
	SELECT e.chain_digest FROM defaultdb.trappoint_ref.cr_event AS e WHERE (e.cr_id = a_subject_id) AND (e.seq = v_head) INTO v_prev_digest;
	SELECT digest(COALESCE(string_agg((bc.check_id::STRING || ':') || d.disposition_id::STRING, '|' ORDER BY bc.check_id::STRING, d.disposition_id::STRING), ''), 'sha256') FROM defaultdb.trappoint_ref.blocking_check AS bc JOIN defaultdb.trappoint_ref.disposition AS d ON (d.check_id = bc.check_id) AND (d.retracted_by IS NULL) WHERE bc.cr_id = a_subject_id INTO v_clearance;
	INSERT INTO defaultdb.trappoint_ref.cr_event(cr_id, seq, prev_seq, from_state, to_state, subject_kind, actor_sub, payload, prev_digest) VALUES (a_subject_id, v_head + 1, v_head, v_state, 'merged', 'change_request', a_merged_by, a_payload || jsonb_build_object('gate_observed_open', v_open, 'gate_epoch', v_epoch), COALESCE(v_prev_digest, decode(repeat('00':::STRING, 32:::INT8), 'hex':::STRING)));
	INSERT INTO defaultdb.trappoint_ref.merge_record(subject_kind, subject_id, cr_id, gate_epoch, merged_by, merged_commit, clearance_digest) VALUES ('change_request', a_subject_id, a_subject_id, v_epoch, a_merged_by, a_merged_commit, v_clearance);
	UPDATE defaultdb.trappoint_ref.change_request SET state = 'merged', head_seq = v_head + 1, merged_commit = a_merged_commit WHERE (cr_id = a_subject_id) AND (head_seq = v_head) RETURNING head_seq INTO v_new_head;
	IF v_new_head IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: merge refused by trappoint_ref.merge_change_request':::STRING || e' \U00002014 the head moved under the gate transaction':::STRING;
	END IF;
	END;
$$
-- ── FUNCTION merge_permit ───────────────
CREATE PROCEDURE trappoint_ref.merge_permit(a_subject_id UUID, a_merged_commit BYTES, a_merged_by STRING, a_actor_kind STRING, a_payload JSONB, a_canon_bytes BYTES, a_payload_ver INT2, a_leaf_hash BYTES)
	LANGUAGE plpgsql
	SECURITY INVOKER
	AS $$
	DECLARE
	v_state trappoint_ref.subject_state;
	v_head INT8;
	v_epoch INT8;
	v_open INT8;
	v_prev_digest BYTES;
	v_clearance BYTES;
	v_new_head INT8;
	BEGIN
	SELECT t.state, t.head_seq, t.gate_epoch FROM defaultdb.trappoint_ref.permit AS t WHERE t.permit_id = a_subject_id FOR UPDATE INTO v_state, v_head, v_epoch;
	IF v_state IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: merge refused by trappoint_ref.merge_permit':::STRING || e' \U00002014 no permit with that identifier':::STRING;
	END IF;
	SELECT count(*) FROM (SELECT 1 FROM defaultdb.trappoint_ref.blocking_check AS bc WHERE (bc.permit_id = a_subject_id) AND (NOT EXISTS (SELECT 1 FROM defaultdb.trappoint_ref.disposition AS d WHERE ((d.check_id = bc.check_id) AND (d.retracted_by IS NULL)) AND ((d.expires_at IS NULL) OR (d.expires_at > now():::TIMESTAMPTZ)))) FOR SHARE) AS locked INTO v_open;
	SELECT e.chain_digest FROM defaultdb.trappoint_ref.permit_event AS e WHERE (e.permit_id = a_subject_id) AND (e.seq = v_head) INTO v_prev_digest;
	SELECT digest(COALESCE(string_agg((bc.check_id::STRING || ':') || d.disposition_id::STRING, '|' ORDER BY bc.check_id::STRING, d.disposition_id::STRING), ''), 'sha256') FROM defaultdb.trappoint_ref.blocking_check AS bc JOIN defaultdb.trappoint_ref.disposition AS d ON (d.check_id = bc.check_id) AND (d.retracted_by IS NULL) WHERE bc.permit_id = a_subject_id INTO v_clearance;
	INSERT INTO defaultdb.trappoint_ref.permit_event(permit_id, seq, prev_seq, from_state, to_state, subject_kind, actor_sub, payload, prev_digest) VALUES (a_subject_id, v_head + 1, v_head, v_state, 'merged', 'permit', a_merged_by, a_payload || jsonb_build_object('gate_observed_open', v_open, 'gate_epoch', v_epoch), COALESCE(v_prev_digest, decode(repeat('00':::STRING, 32:::INT8), 'hex':::STRING)));
	INSERT INTO defaultdb.trappoint_ref.merge_record(subject_kind, subject_id, permit_id, gate_epoch, merged_by, merged_commit, clearance_digest) VALUES ('permit', a_subject_id, a_subject_id, v_epoch, a_merged_by, a_merged_commit, v_clearance);
	UPDATE defaultdb.trappoint_ref.permit SET state = 'merged', head_seq = v_head + 1, merged_commit = a_merged_commit WHERE (permit_id = a_subject_id) AND (head_seq = v_head) RETURNING head_seq INTO v_new_head;
	IF v_new_head IS NULL THEN
		RAISE EXCEPTION
	USING ERRCODE = 'P0001',
	MESSAGE = 'TRAPPOINT_REF: merge refused by trappoint_ref.merge_permit':::STRING || e' \U00002014 the head moved under the gate transaction':::STRING;
	END IF;
	END;
$$
-- ── TRIGGER blocking_check.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.blocking_check FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER blocking_check.check_materialised ───────────────
CREATE TRIGGER check_materialised AFTER INSERT ON defaultdb.trappoint_ref.blocking_check FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_check_materialised();
-- ── TRIGGER blocking_check.check_project ───────────────
CREATE TRIGGER check_project BEFORE INSERT ON defaultdb.trappoint_ref.blocking_check FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_check_project();
-- ── TRIGGER change_request.cr_merge_gate ───────────────
CREATE TRIGGER cr_merge_gate BEFORE UPDATE ON defaultdb.trappoint_ref.change_request FOR EACH ROW WHEN ((new).state = 'merged':::trappoint_ref.subject_state) AND ((old).state != 'merged':::trappoint_ref.subject_state) EXECUTE FUNCTION defaultdb.trappoint_ref.fn_cr_merge_gate();
-- ── TRIGGER clause_blame_closure.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.clause_blame_closure FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER clause_blame_closure.closure_guard ───────────────
CREATE TRIGGER closure_guard BEFORE INSERT ON defaultdb.trappoint_ref.clause_blame_closure FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_closure_guard();
-- ── TRIGGER clause_version.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.clause_version FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER cr_event.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.cr_event FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER cr_event.cr_event_chain ───────────────
CREATE TRIGGER cr_event_chain BEFORE INSERT ON defaultdb.trappoint_ref.cr_event FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_cr_event_chain();
-- ── TRIGGER disposition.disposition_close ───────────────
CREATE TRIGGER disposition_close AFTER INSERT ON defaultdb.trappoint_ref.disposition FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_disposition_close();
-- ── TRIGGER disposition.disposition_project ───────────────
CREATE TRIGGER disposition_project BEFORE INSERT ON defaultdb.trappoint_ref.disposition FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_disposition_project();
-- ── TRIGGER disposition.disposition_retract_only ───────────────
CREATE TRIGGER disposition_retract_only BEFORE UPDATE ON defaultdb.trappoint_ref.disposition FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_disposition_retract_only();
-- ── TRIGGER exposure_line.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.exposure_line FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER exposure_receipt.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.exposure_receipt FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER merge_record.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.merge_record FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER override_ledger.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.override_ledger FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER permit.permit_merge_gate ───────────────
CREATE TRIGGER permit_merge_gate BEFORE UPDATE ON defaultdb.trappoint_ref.permit FOR EACH ROW WHEN ((new).state = 'merged':::trappoint_ref.subject_state) AND ((old).state != 'merged':::trappoint_ref.subject_state) EXECUTE FUNCTION defaultdb.trappoint_ref.fn_permit_merge_gate();
-- ── TRIGGER permit_event.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.permit_event FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER permit_event.permit_event_chain ───────────────
CREATE TRIGGER permit_event_chain BEFORE INSERT ON defaultdb.trappoint_ref.permit_event FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_permit_event_chain();
-- ── TRIGGER person.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.person FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
-- ── TRIGGER signing_credential.append_only ───────────────
CREATE TRIGGER append_only BEFORE UPDATE OR DELETE ON defaultdb.trappoint_ref.signing_credential FOR EACH ROW EXECUTE FUNCTION defaultdb.trappoint_ref.fn_refuse_mutation();
