# SPDX-FileCopyrightText: 2026 MAINLINE contributors
# SPDX-License-Identifier: Apache-2.0
"""Reciprocal Rank Fusion over channels C and D. Channels A and B never enter here.

Two properties do all the work, and both are structural rather than asserted at run time.

**Rank, not score.** RRF combines *positions*, so a BM25 score in the tens and a cosine
distance in the unit interval need no normalisation, no z-scoring and no per-corpus
rescaling — the three places where a fusion implementation usually acquires a hidden tuning
knob. :func:`reciprocal_rank_fusion` therefore accepts ordered ``doc_id`` sequences and has
no parameter through which a raw score could reach it. Callers holding scores convert with
:func:`rank_from_scores`, whose output is invariant under every strictly increasing
transform of those scores; that invariance is what
``tests/unit/recall_fusion/test_rrf.py`` pins.

**Channels A and B are refused, not ignored.** Deterministic ancestry and the bonded
severity-5 set are admitted unconditionally (ARCHITECTURE 6.4); fusing them would put a
fatality's admission at the mercy of a rank arithmetic, and MI16
(``bonded_fatalities_all_blocking``) would become a property of a weighting rather than of
the schema. Handing this function an arm on channel A or B raises
:class:`ChannelBypassesFusion` — a caller that made that mistake has a design bug, and a
silently-fused fatality is precisely the failure the product exists to prevent.

The constant ``k = 60`` is Cormack, Clarke and Buettcher (2009). It is a published default,
not a fitted one; a deployment that wants a different value passes it and records it in
``mainline_meas.recall_policy.arms`` beside the per-arm weights, because a fusion constant
decides which precursor outranks which and is therefore an exhibit.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Final

__all__ = [
    "CHANNEL_BIT",
    "FUSED_CHANNELS",
    "RRF_K",
    "ArmRanking",
    "ChannelBypassesFusion",
    "Contribution",
    "FusedCandidate",
    "InvalidRanking",
    "channel_mask_of",
    "rank_from_scores",
    "reciprocal_rank_fusion",
]

RRF_K: Final = 60
"""Cormack et al. 2009. Damps the contribution of any single arm's top position so one
over-confident arm cannot carry a candidate on its own."""

CHANNEL_BIT: Final[Mapping[str, int]] = {"C": 1, "C_sweep": 2, "D": 4}
"""Bit positions for :attr:`FusedCandidate.channel_mask`, which becomes a feature slot.
A stable integer rather than a set, because it is written into
``mainline_meas.recall_candidate.features`` and re-read by a stranger."""

FUSED_CHANNELS: Final[frozenset[str]] = frozenset(CHANNEL_BIT)
"""C (prefix-constrained ANN), C_sweep (the 256-d coarse sweep), D (lexical BM25)."""

BYPASS_CHANNELS: Final[frozenset[str]] = frozenset({"A", "B"})
"""Deterministic ancestry and the bonded severity-5 set. Blocking unconditionally."""


class InvalidRanking(ValueError):
    """An arm ranking that cannot be fused: bad weight, repeated document, unknown channel.

    Never defaulted. A defaulted arm weight is a change to which precursor outranks which,
    made without a policy commit saying so.
    """


class ChannelBypassesFusion(InvalidRanking):
    """Channel A or B was handed to the fuser.

    Both are admitted unconditionally by the orchestrator. Fusing them would make a
    fatality's admission depend on rank arithmetic, which is exactly what
    ``bonded_fatalities_all_blocking`` exists to prevent.
    """


@dataclass(frozen=True, slots=True)
class ArmRanking:
    """One arm's ordered result list, plus the weight the policy gave that arm.

    Attributes:
        arm_id: Stable arm identity, as generated by :mod:`trappoint_recall.arms`. It
            appears in every contribution so a fused score can be traced to the index
            lookups that produced it.
        channel: One of :data:`FUSED_CHANNELS`.
        weight: Multiplier on this arm's reciprocal-rank contribution, supplied by the
            caller from ``recall_policy.arms``. Strictly positive: a zero-weight arm that
            still appears in the record would claim an index lookup contributed something
            when it could not.
        doc_ids: Result identifiers in rank order. Position 0 is rank 1.
    """

    arm_id: str
    channel: str
    weight: float
    doc_ids: tuple[str, ...]

    def __post_init__(self) -> None:
        if not self.arm_id:
            raise InvalidRanking("arm_id must be non-empty: it names the lookup that fired")
        if self.channel in BYPASS_CHANNELS:
            raise ChannelBypassesFusion(
                f"arm {self.arm_id!r} declares channel {self.channel!r}. Channels A "
                "(deterministic ancestry) and B (bonded severity-5) are admitted "
                "unconditionally and must never be fused: a fused fatality is a fatality "
                "whose admission depends on a weight."
            )
        if self.channel not in FUSED_CHANNELS:
            raise InvalidRanking(
                f"arm {self.arm_id!r} declares unknown channel {self.channel!r}; "
                f"fusable channels are {sorted(FUSED_CHANNELS)}"
            )
        if not math.isfinite(self.weight) or self.weight <= 0.0:
            raise InvalidRanking(
                f"arm {self.arm_id!r} has weight {self.weight!r}; weights must be finite "
                "and strictly positive"
            )
        seen: set[str] = set()
        for doc_id in self.doc_ids:
            if not doc_id:
                raise InvalidRanking(f"arm {self.arm_id!r} contains an empty doc_id")
            if doc_id in seen:
                raise InvalidRanking(
                    f"arm {self.arm_id!r} returns {doc_id!r} twice. One arm is one index "
                    "lookup; a repeated document would count its own rank twice."
                )
            seen.add(doc_id)


@dataclass(frozen=True, slots=True)
class Contribution:
    """What one arm contributed to one candidate's fused score.

    Retained rather than summed away: ``increment`` is the arithmetic a supervisor is
    entitled to see behind a blocking check, and a fused score with no decomposition is a
    number nobody can argue with.
    """

    arm_id: str
    channel: str
    rank: int
    weight: float
    increment: float

    def to_json(self) -> dict[str, float | int | str]:
        return {
            "arm_id": self.arm_id,
            "channel": self.channel,
            "rank": self.rank,
            "weight": self.weight,
            "increment": self.increment,
        }


@dataclass(frozen=True, slots=True)
class FusedCandidate:
    """One document, its fused score, and every arm that voted for it."""

    doc_id: str
    rrf_score: float
    best_arm_rank: int
    best_arm_id: str
    channel_mask: int
    contributions: tuple[Contribution, ...]
    rank: int

    @property
    def coarse_only(self) -> bool:
        """True when the coarse sweep is the *only* channel that found this document.

        ARCHITECTURE 6.4: a sweep hit is never blocking unless severity is 5. The flag is
        carried as a feature so the admission arithmetic can apply that rule without
        re-deriving it from the contribution list.
        """
        return self.channel_mask == CHANNEL_BIT["C_sweep"]

    @property
    def channels(self) -> tuple[str, ...]:
        return tuple(name for name, bit in CHANNEL_BIT.items() if self.channel_mask & bit)

    def to_json(self) -> dict[str, object]:
        return {
            "doc_id": self.doc_id,
            "rrf_score": self.rrf_score,
            "best_arm_rank": self.best_arm_rank,
            "best_arm_id": self.best_arm_id,
            "channel_mask": self.channel_mask,
            "coarse_only": self.coarse_only,
            "rank": self.rank,
            "contributions": [c.to_json() for c in self.contributions],
        }


def channel_mask_of(channels: Iterable[str]) -> int:
    """Fold channel names into the bitmask feature slot."""
    mask = 0
    for channel in channels:
        try:
            mask |= CHANNEL_BIT[channel]
        except KeyError as exc:
            raise InvalidRanking(f"unknown channel {channel!r}") from exc
    return mask


def rank_from_scores(
    scored: Mapping[str, float] | Sequence[tuple[str, float]],
    *,
    descending: bool = True,
) -> tuple[str, ...]:
    """Convert an arm's raw scores to the rank order RRF consumes.

    This is the only place a raw score is allowed near the fuser, and it discards the
    magnitudes on the way out. The result is therefore invariant under every strictly
    increasing transform of the input scores — the property that lets a cosine arm and a
    BM25 arm be combined without either one's distribution being a hidden parameter.

    Ties break on ``doc_id`` ascending, so two arms that disagree only within a tie
    produce the same fused set on every machine.

    Args:
        scored: ``doc_id -> score`` mapping, or an iterable of pairs.
        descending: ``True`` when a larger score is better (cosine similarity, BM25),
            ``False`` for a distance.

    Raises:
        InvalidRanking: on a repeated ``doc_id`` or a non-finite score.
    """
    pairs = list(scored.items()) if isinstance(scored, Mapping) else list(scored)
    seen: set[str] = set()
    for doc_id, score in pairs:
        if doc_id in seen:
            raise InvalidRanking(f"{doc_id!r} appears twice in one arm's score list")
        seen.add(doc_id)
        if not math.isfinite(score):
            raise InvalidRanking(f"{doc_id!r} has non-finite score {score!r}")
    sign = -1.0 if descending else 1.0
    pairs.sort(key=lambda pair: (sign * pair[1], pair[0]))
    return tuple(doc_id for doc_id, _ in pairs)


def reciprocal_rank_fusion(
    rankings: Sequence[ArmRanking], *, k: int = RRF_K
) -> tuple[FusedCandidate, ...]:
    """Weighted RRF over channel C, the coarse sweep and channel D.

    ``score(d) = sum over arms a containing d of weight(a) / (k + rank(d, a))``

    Args:
        rankings: One entry per arm, each already in rank order.
        k: The RRF damping constant. Recorded in the policy, never tuned per run.

    Returns:
        Candidates sorted by fused score descending, with ties broken by best arm rank and
        then ``doc_id``, each carrying its 1-based fused ``rank``.

    Raises:
        ChannelBypassesFusion: if any ranking declares channel A or B.
        InvalidRanking: on a malformed ranking or a non-positive ``k``.
    """
    if k <= 0:
        raise InvalidRanking(f"RRF k must be positive, got {k}")

    arm_ids: set[str] = set()
    accumulated: dict[str, list[Contribution]] = {}
    scores: dict[str, float] = {}

    for ranking in rankings:
        if ranking.arm_id in arm_ids:
            raise InvalidRanking(
                f"arm {ranking.arm_id!r} appears twice. Two rankings under one arm id "
                "would double that arm's weight without any policy row saying so."
            )
        arm_ids.add(ranking.arm_id)
        for position, doc_id in enumerate(ranking.doc_ids, start=1):
            increment = ranking.weight / (k + position)
            accumulated.setdefault(doc_id, []).append(
                Contribution(
                    arm_id=ranking.arm_id,
                    channel=ranking.channel,
                    rank=position,
                    weight=ranking.weight,
                    increment=increment,
                )
            )
            scores[doc_id] = scores.get(doc_id, 0.0) + increment

    fused: list[FusedCandidate] = []
    for doc_id, contributions in accumulated.items():
        ordered = tuple(sorted(contributions, key=lambda c: (c.rank, c.arm_id)))
        best = ordered[0]
        fused.append(
            FusedCandidate(
                doc_id=doc_id,
                rrf_score=scores[doc_id],
                best_arm_rank=best.rank,
                best_arm_id=best.arm_id,
                channel_mask=channel_mask_of(c.channel for c in ordered),
                contributions=ordered,
                rank=0,
            )
        )

    fused.sort(key=lambda c: (-c.rrf_score, c.best_arm_rank, c.doc_id))
    return tuple(
        FusedCandidate(
            doc_id=c.doc_id,
            rrf_score=c.rrf_score,
            best_arm_rank=c.best_arm_rank,
            best_arm_id=c.best_arm_id,
            channel_mask=c.channel_mask,
            contributions=c.contributions,
            rank=position,
        )
        for position, c in enumerate(fused, start=1)
    )
